### ISSUE TITLE
Fallback agent fails due to Python KeyError

### ISSUE THREAD

**Issue by mwhdc** [m50/ha-fallback-conversation#14]
I believe this error appeared with 2024.6.0 so there may have been another breaking change in the assist pipeline right after the integration's last release.

Occurs with either Gemini or OpenAI as fallback agent, with or without assist or recommended model settings. Inline error message in the conversation is "Unexpected error during intent recognition" in red bubble.

```
2024-06-11 11:16:23.360 ERROR (MainThread) [homeassistant.components.assist_pipeline.pipeline] Unexpected error during intent recognition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 994, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 108, in async_converse
    result = await method(conversation_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fallback_conversation/__init__.py", line 90, in async_process
    agent_names[agent_id],
    ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'conversation.gemini'
```

**Comment by ov1d1u** [comment]
Please try my fork: https://github.com/ov1d1u/ha-fallback-conversation. If it works, I will create a PR.

**Comment by mwhdc** [comment]
> Please try my fork: https://github.com/ov1d1u/ha-fallback-conversation. If it works, I will create a PR.

Working here! Thanks for the fix.

**Comment by cooljimy84** [comment]
fixes my issue as well, thanks.

**Comment by m50** [comment]
I merged the PR for it. I apologize about the delay.

**Comment by styphonthal** [comment]
I don't think this has fixed it for Openai, I updated this morning and still get this error

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 994, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 108, in async_converse
    result = await method(conversation_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fallback_conversation/__init__.py", line 90, in async_process
    agent_names[agent_id],
    ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'ec096d1807e1cc6a84562ffa2c44f4db'
