### ISSUE TITLE
[Bug] Error when trying to use with HomeLLM and LocalAI integration with Llama3

### ISSUE THREAD

**Issue by maxi1134** [m50/ha-fallback-conversation#19]
Hi there,

I am currently running `https://github.com/acon96/home-llm` to integrate an LLM running on `https://github.com/mudler/LocalAI/` on a dedicated host.

I tried installing this here present integration to be able to fallback to my LLM when HA is unable to detect an intent.

Unfortunately, I get the following error when trying to use it:

```
2024-07-03 10:30:53.525 ERROR (MainThread) [homeassistant.components.assist_pipeline.pipeline] Unexpected error during intent recognition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 994, in recognize_intent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 994, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 108, in async_converse
    result = await method(conversation_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 108, in async_converse
    result = await method(conversation_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fallback_conversation/__init__.py", line 91, in async_process
  File "/config/custom_components/fallback_conversation/__init__.py", line 91, in async_process
    agent_names[agent_id] or "[unknown]",
    agent_names[agent_id] or "[unknown]",
    ~~~~~~~~~~~^^^^^^^^^^
KeyError: '57b7a9c84a4a8309ee119ee12bb3bf70'
    ~~~~~~~~~~~^^^^^^^^^^
KeyError: '57b7a9c84a4a8309ee119ee12bb3bf70'
```

And a few screenshots:

![image](https://github.com/m50/ha-fallback-conversation/assets/1342643/ee565876-7223-4abf-8633-4fb2c87d8a63)
![image](https://github.com/m50/ha-fallback-conversation/assets/1342643/1ef42f1c-c132-426d-8529-3075f9da3763)

Thanks!

**Comment by m50** [comment]
Seems to be the same issue as in #17 . I am going to close this for now, but when #17 is resolved, if this is not fixed at the same time, please re-open this and I'll dig back into it.
