### ISSUE TITLE
HassNevermind causes error

### ISSUE THREAD

**Issue by 33masterman33** [m50/ha-fallback-conversation#42]
Functionally is unaffected from my limited testing. Please let me know if you need any additional information.

```Logger: homeassistant.components.assist_pipeline.pipeline
Source: components/assist_pipeline/pipeline.py:1017
integration: Assist pipeline (documentation, issues)
First occurred: 8:03:27 AM (2 occurrences)
Last logged: 8:06:51 AM

Unexpected error during intent recognition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1017, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 110, in async_converse
    result = await method(conversation_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/entity.py", line 47, in internal_async_process
    return await self.async_process(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fallback_conversation/conversation.py", line 126, in async_process
    result = await self._async_process_agent(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fallback_conversation/conversation.py", line 173, in _async_process_agent
    r = result.response.speech['plain']['speech']
        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'plain'
```

Edited to fix code block.

**Comment by m50** [comment]
Due to Home Assistant implementing this functionality internally, I will no longer be maintaining this. Sorry
